package com.food.city.dto;

import com.food.city.model.Restaurant;
import io.swagger.annotations.ApiModelProperty;
import org.springframework.hateoas.RepresentationModel;


public class RestaurantRepresentation extends RepresentationModel<Restaurant> {

    @ApiModelProperty(value = "autogenerated id")
    private  Long id;
    @ApiModelProperty(value = "Name of Restaurant")
    private String name;
    @ApiModelProperty(value = "Price range of Restaurant")
    private Integer price;
    @ApiModelProperty(value = "Cusine category serve by restaurant")
    private String cusine_category;
    @ApiModelProperty(value = "Restaurant in a City")
    private String city;
    @ApiModelProperty(value = "Restaurant in a Region")
    private String region;
    @ApiModelProperty(value = "Zomato url of restaurant")
    private String url;
    @ApiModelProperty(value = "Cusine Type serve by restaurant")
    private String cusine_type;
    @ApiModelProperty(value = "Timing of Restaurant")
    private String time;
    @ApiModelProperty(value = "Rating of Restaurant")
    private Float rating;
    @ApiModelProperty(value = "Rating type of Restaurant")
    private String rating_type;
    @ApiModelProperty(value = "Number of people voted for Restaurant")
    private String votes;

    public RestaurantRepresentation() {
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    public void setCusine_category(String cusine_category) {
        this.cusine_category = cusine_category;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public void setCusine_type(String cusine_type) {
        this.cusine_type = cusine_type;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public void setRating(Float rating) {
        this.rating = rating;
    }

    public void setRating_type(String rating_type) {
        this.rating_type = rating_type;
    }

    public void setVotes(String votes) {
        this.votes = votes;
    }

    public Long getId() {
        return this.id;
    }

    public String getName(String name) {
        return this.name;
    }

    public Integer getPrice() {
        return price;
    }

    public String getCusine_category() {
        return cusine_category;
    }

    public String getCity() {
        return city;
    }

    public String getRegion() {
        return region;
    }

    public String getUrl() {
        return url;
    }

    public String getCusine_type() {
        return cusine_type;
    }

    public String getTime() {
        return time;
    }

    public Float getRating() {
        return rating;
    }

    public String getRating_type() {
        return rating_type;
    }

    public String getVotes() {
        return votes;
    }

    public RestaurantRepresentation(Long id, String name, Integer price, String cusine_category, String city, String region, String url, String cusine_type, String time, Float rating, String rating_type, String votes) {
        this.id = id;
        this.name = name;
        this.price = price;
        this.cusine_category = cusine_category;
        this.city = city;
        this.region = region;
        this.url = url;
        this.cusine_type = cusine_type;
        this.time = time;
        this.rating = rating;
        this.rating_type = rating_type;
        this.votes = votes;
    }

}
